### ISSUE TITLE
Dev React Native - BH/MG Presencial

### ISSUE THREAD

**Issue by GuilhermeSinaxys** [react-native-drops/vagas#14]
Olá colegas, bom dia.

Sou o Guilherme, parte do time Sinaxys. Uma Healthtech fundada em 2017 focada em vagas e network para profissionais de saúde.

Estamos com algumas vagas em aberto, e uma delas é para Desenvolvedor React Native. Procuramos por profissionais preferencialmente de BH onde dispomos de escritorio sede da empresa. 

Caso se interesse, por favor mande seu currículo para guilherme@sinaxys.com que entraremos em contato para marcar um bate papo rápido e passar mais detalhes.

Grande abraço.

sinaxys.com

**Comment by gustavocoimbraold** [comment]
Bom dia, Guilherme. Alguma oportunidade no momento?
