### ISSUE TITLE
Branch main - Criar automações

### ISSUE THREAD

**Issue by guibranco** [react-native-drops/vagas#143]
Gostaria de solicitar a criação da branch `main` assim seria possível:

- Criar `Issue template` para padronizar o envio de vagas.
- Action para `fechar issues` antigas / sem atividade e manter apenas as vagas recentes em aberto.
- Action para `adicionar labels automaticamente` nas issues criadas/editadas, assim facilita a filtragem pelos possíveis candidatos.

Basta criar a branch main no repositório, ou habilitar o fork do repositório, assim eu consigo criar os arquivos/códigos necessários e submeter via `pull request` para que vocês possam revisar e aprovar (ou solicitar alguma modificação).

**Comment by guibranco** [comment]
@josenaves @rafaellincoln @kevinbreaker

**Comment by guibranco** [comment]
Poderiam dar uma olhada nessa issue por favor ? @josenaves @rafaellincoln @kevinbreaker

**Comment by josenaves** [comment]
Criei a branch master
