### ISSUE TITLE
[ híbrido ] dev mobile / frontend Jr

### ISSUE THREAD

**Issue by devgmaisp** [react-native-drops/vagas#144]
Vaga dev Jr frontend / mobile 
- local : Barra da tijuca - rio de janeiro
- Remuneração : 2500 ( pj) + VR + VT
- forma : híbrido  - 2 x escritório - 3x  home office 
Requisitos:
- React Native - expo 
- React.js 
- vue.js
- html 
- css
- javascript
- consumo de api rest
Contato :  mateus@gmaisp.com.br
Ou outro contato +5521974830854

**Comment by MaykonCWB** [comment]
Aceita candidatos Home-Office ?
