### ISSUE TITLE
[REMOTO] - Freelance RN para conluir projeto

### ISSUE THREAD

**Issue by fwsilva** [react-native-drops/vagas#97]
Oi pessoal, estou desenvolvimento um app para publico feminino em React Native e estou precisando de outra mão para agilizar o desenvolvimento. 
Quem tiver interesse e disponibilidaed deixa um comentario que chamo para ouvir propostas , combinar pagamento etc

**Comment by eusouwilson** [comment]
Vamos conversar sobre isso
98992044217

**Comment by MarceloMafraBJJ** [comment]
Tenho interesse, pode me chamar no WhatsApp. 48 999759801
